'use strict';

var ApiErrors = function () { };

ApiErrors.EMAIL_NOT_FOUND = 0;
ApiErrors.INVALID_PWD = 1;
ApiErrors.DB_ERROR = 2;
ApiErrors.NOT_FOUND = 3;
ApiErrors.EMAIL_ALREADY_EXISTS = 4;
ApiErrors.COULD_NOT_CREATE_USER = 5;
ApiErrors.PASSWORD_RESET_EXPIRED = 6;
ApiErrors.PASSWORD_RESET_HASH_MISMATCH = 7;
ApiErrors.PASSWORD_RESET_EMAIL_MISMATCH = 8;
ApiErrors.COULD_NOT_RESET_PASSWORD = 9;
ApiErrors.INVALID_TOKEN = 10;
ApiErrors.INVALID_PARAMETER = 11;
ApiErrors.INTERNAL_SERVER_ERROR = 12;
ApiErrors.PASSWORD_RESET_ALREADY_SENT = 13;
ApiErrors.USER_NOT_LOGGED_IN = 14;
ApiErrors.VIDEO_ACCESS_ERROR = 15;
ApiErrors.CONNECTION_DOES_NOT_EXIST = 16;
ApiErrors.CONNECTION_ALREADY_PENDING = 17;
ApiErrors.CONNECTION_ALREADY_EXISTS = 18;
ApiErrors.ACCEPT_INVITE_DOES_NOT_EXIST = 19;

module.exports = ApiErrors;
